export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
] as const;

export type IndianState = (typeof INDIAN_STATES)[number];

// Popular destinations for fuzzy matching fallback
export const POPULAR_DESTINATIONS = [
  { name: "Varanasi", state: "Uttar Pradesh", aliases: ["banaras", "kashi", "benaras", "varnasi"] },
  { name: "Jaipur", state: "Rajasthan", aliases: ["pink city", "jeypore"] },
  { name: "Udaipur", state: "Rajasthan", aliases: ["city of lakes"] },
  { name: "Goa", state: "Goa", aliases: ["panaji", "north goa", "south goa"] },
  { name: "Manali", state: "Himachal Pradesh", aliases: ["kullu manali", "solang"] },
  { name: "Munnar", state: "Kerala", aliases: ["tea gardens"] },
  { name: "Rishikesh", state: "Uttarakhand", aliases: ["yoga capital", "haridwar"] },
  { name: "Leh Ladakh", state: "Ladakh", aliases: ["leh", "pangong", "nubra"] },
  { name: "Agra", state: "Uttar Pradesh", aliases: ["taj mahal city"] },
  { name: "Kolkata", state: "West Bengal", aliases: ["calcutta", "city of joy"] },
  { name: "Mumbai", state: "Maharashtra", aliases: ["bombay", "marine drive"] },
  { name: "Amritsar", state: "Punjab", aliases: ["golden temple city"] },
];
